#!/usr/bin/php

$client = S3Client::factory();
ENVFILE="/etc/aws-security"

if [ -f $ENVFILE ];
then
    source /etc/aws-security
    export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
    export AWS_SECRET_KEY=$AWS_SECRET_KEY
else
    echo "$ENVFILE does not exist"
    exit 5;
fi

# locate the instance ID of this VM
INSTANCEID="$(ec2-describe-instances | grep "INSTANCE" | grep $(hostname -f) | cut -f2)"

if [ -z "$INSTANCEID" ]; then
    echo "Failed to locate instance ID" >&2
    exit 5;
fi

INSTANCENAME=`ec2-describe-tags --filter "resource-id=$INSTANCEID" --filter "key=Name" | awk '{for (i=1; i<=NF-4; i++) $i = $(i+4); NF-=4; print}'`

echo "Backing up $INSTANCENAME volumes";

# locate the EBS volume ID for the root file system
VOLUMES="$(ec2-describe-volumes | grep "$INSTANCEID" | cut -d' ' -f1 | cut -f 2,4)"

while read -r line; do
    volumeid="$(echo "$line" | cut -f 1)"
    mount="$(echo "$line" | cut -f 2)"

    echo "$volumeid mounted on $mount"
done <<< "$VOLUMES"

